### ISSUE TITLE
Can't make Pull Request

### ISSUE THREAD

**Issue by MoONStterTeixi** [vindecodex/hacktoberfest-OOP#3]
I wanna make some refactor, for exemple tabulation, better structures of foleds and try to add some other exemples but cant do any PR.
Check if able to make it.
![181271a864aa2c2fb95fb63dcaab0661](https://user-images.githubusercontent.com/23308393/195327009-6de67990-3673-45b3-927e-6bd94da0d51b.png)

**Comment by vindecodex** [comment]
Hi @MoONStterTeixi, it's my first time seeing that prompt for public repositories but may I know what happens when you click the `Fork this repository` button?

**Comment by MoONStterTeixi** [comment]
Sorry sir,
Im new too collaborating.
I will hope u see well my PR.

Have a great day.
